# Generated by Django 5.2.15 on 2026-07-06 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0006_alter_application_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="ai_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="application",
            name="ai_strengths",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="application",
            name="ai_summary",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="application",
            name="ai_weaknesses",
            field=models.TextField(blank=True),
        ),
    ]
