# Generated by Django 5.2.15 on 2026-07-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0007_application_ai_score_application_ai_strengths_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("Draft", "Draft"),
                    ("Pending", "Pending"),
                    ("Reviewing", "Reviewing"),
                    ("Shortlisted", "Shortlisted"),
                    ("Interview", "Interview"),
                    ("Rejected", "Rejected"),
                    ("Hired", "Hired"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
