# Generated by Django 5.2.15 on 2026-07-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0008_alter_application_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("Draft", "Draft"),
                    ("Pending", "Pending"),
                    ("Screening", "Screening"),
                    ("Shortlisted", "Shortlisted"),
                    ("Interview", "Interview"),
                    ("Rejected", "Rejected"),
                    ("Hired", "Hired"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
