# Generated by Django 5.2.15 on 2026-07-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0009_alter_application_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="interview_scheduled",
            field=models.BooleanField(default=False),
        ),
    ]
