# Generated by Django 5.2.15 on 2026-07-23 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0010_application_interview_scheduled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Screening", "Screening"),
                    ("Interview", "Interview"),
                    ("Rejected", "Rejected"),
                    ("Hired", "Hired"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[("Active", "Acive"), ("Inactive", "Inactive")],
                default="Open",
                max_length=20,
            ),
        ),
    ]
