# Generated by Django 5.2.15 on 2026-07-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0011_alter_application_status_alter_job_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[("Active", "Active"), ("Inactive", "Inactive")],
                default="Open",
                max_length=20,
            ),
        ),
    ]
