# Generated by Django 5.2.15 on 2026-07-23 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0012_alter_job_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="is_active",
        ),
    ]
