# Generated by Django 6.0.3 on 2026-09-04 08:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_application_applicant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status'], name='jobs_applic_status_f83260_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['job', 'status'], name='jobs_applic_job_id_a25382_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['-ai_score', '-created_at'], name='jobs_applic_ai_scor_f20744_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status'], name='jobs_job_status_7d017a_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['department', 'status'], name='jobs_job_departm_844426_idx'),
        ),
    ]
