# Generated by Django 6.0.3 on 2026-08-31 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_application_applicant'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='key_qualifications',
            field=models.TextField(blank=True, help_text='Important qualifications used by AI screening. Not visible to applications.'),
        ),
    ]
