# Generated by Django 6.0.3 on 2026-08-31 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_job_key_qualifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='key_qualifications',
        ),
        migrations.AddField(
            model_name='job',
            name='requirements',
            field=models.TextField(blank=True),
        ),
    ]
