# Generated by Django 6.0.3 on 2026-08-31 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_remove_job_key_qualifications_job_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='key_qualifications',
            field=models.TextField(blank=True),
        ),
    ]
