# Generated by Django 6.0.3 on 2026-09-05 19:46

import jobs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_application_jobs_applic_applica_a398e7_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(upload_to=jobs.models.application_resume_upload_path),
        ),
    ]
