# Generated by Django 6.0.3 on 2026-08-31 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_job_key_qualifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='key_qualifications',
        ),
    ]
