# Generated by Django 6.0.3 on 2026-09-07 08:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_alter_application_resume'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['job', '-ai_score', '-created_at'], name='jobs_applic_job_id_452889_idx'),
        ),
    ]
