# Generated by Django 6.0.3 on 2026-08-31 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0019_remove_job_key_qualifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ai_education_match',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='ai_experience_match',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='ai_match_level',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='application',
            name='ai_matched_qualifications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='ai_missing_qualifications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='ai_qualification_match',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='ai_recommendation',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='application',
            name='ai_skills_match',
            field=models.IntegerField(default=0),
        ),
    ]
