# Generated by Django 6.0.3 on 2026-09-05 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_application_jobs_applic_status_f83260_idx_and_more'),
        ('jobs', '0020_application_ai_education_match_and_more'),
    ]

    operations = [
    ]
