# Generated by Django 6.0.3 on 2026-09-05 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0021_merge_20260906_0254'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='job',
            name='jobs_job_status_7d017a_idx',
        ),
        migrations.RemoveIndex(
            model_name='job',
            name='jobs_job_departm_844426_idx',
        ),
    ]
