# Generated by Django 6.0.3 on 2026-09-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0022_remove_job_jobs_job_status_7d017a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ai_criteria_weights',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='application',
            name='ai_weight_reasoning',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
