# Generated by Django 6.0.3 on 2026-09-08 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0019_application_jobs_applic_job_id_452889_idx'),
        ('jobs', '0023_application_ai_criteria_weights_and_more'),
    ]

    operations = [
    ]
