# Generated by Django 6.0.3 on 2026-09-09 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0024_merge_20260909_0347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='requirement',
            options={'verbose_name': 'Key Qualification', 'verbose_name_plural': 'Key Qualifications'},
        ),
        migrations.AlterField(
            model_name='job',
            name='requirements',
            field=models.TextField(blank=True, help_text='Applicant-facing requirements shown directly on the job posting (education, general experience, etc.).', verbose_name='General Requirements'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='text',
            field=models.CharField(help_text='Specific qualification used by the AI during candidate screening (e.g. Python, B2B Sales, AWS).', max_length=255, verbose_name='Key Qualification'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status'], name='jobs_job_status_7d017a_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['department', 'status'], name='jobs_job_departm_844426_idx'),
        ),
    ]
