# Generated by Django 6.0.3 on 2026-09-09 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0025_department_alter_requirement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='schedule',
            field=models.CharField(blank=True, default='', help_text='Working days (e.g. Monday to Friday, Weekends)', max_length=100, verbose_name='Work Schedule'),
        ),
        migrations.AddField(
            model_name='job',
            name='shift',
            field=models.CharField(blank=True, default='', help_text='Working hours (e.g. 8:00 AM - 5:00 PM, Night Shift)', max_length=100, verbose_name='Shift Hours'),
        ),
    ]
