# Generated by Django 6.0.3 on 2026-09-14 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0025_job_jobs_job_status_7d017a_idx_and_more"),
        ("jobs", "0026_job_schedule_job_shift"),
    ]

    operations = []
