# Generated by Django 6.0.3 on 2026-09-15 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0027_merge_20260914_1419'),
        ('jobs', '0027_merge_20260914_1442'),
    ]

    operations = [
    ]
