# Generated by Django 6.0.3 on 2026-09-16 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0028_merge_20260915_1321"),
        ("jobs", "0028_merge_20260915_1739"),
    ]

    operations = []
