# Generated by Django 6.0.3 on 2026-09-17 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0029_merge_20260915_2039'),
        ('jobs', '0030_application_unique_applicant_job_application'),
    ]

    operations = [
    ]
