# Generated by Django 6.0.3 on 2026-09-22 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0031_merge_20260917_2231"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Screening", "Screening"),
                    ("Interview", "Interview"),
                    ("Rejected", "Rejected"),
                    ("Hired", "Hired"),
                ],
                default="Screening",
                max_length=20,
            ),
        ),
    ]
