# Generated by Django 6.0.3 on 2026-09-24 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0033_alter_application_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Screening", "Screening"),
                    ("Shortlisted", "Shortlisted"),
                    ("Interview", "Interview"),
                    ("Evaluation", "Evaluation"),
                    ("Hired", "Hired"),
                    ("Rejected", "Rejected"),
                ],
                default="Screening",
                max_length=20,
            ),
        ),
    ]
