# Generated by Django 6.0.3 on 2026-09-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0034_alter_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='education_weight',
            field=models.PositiveIntegerField(default=25, help_text='Weight percentage for Education in candidate screening.', verbose_name='Education Weight'),
        ),
        migrations.AddField(
            model_name='job',
            name='experience_weight',
            field=models.PositiveIntegerField(default=25, help_text='Weight percentage for Experience in candidate screening.', verbose_name='Experience Weight'),
        ),
        migrations.AddField(
            model_name='job',
            name='qualification_weight',
            field=models.PositiveIntegerField(default=25, help_text='Weight percentage for Key Qualifications in candidate screening.', verbose_name='Qualification Weight'),
        ),
        migrations.AddField(
            model_name='job',
            name='skills_weight',
            field=models.PositiveIntegerField(default=25, help_text='Weight percentage for Skills in candidate screening.', verbose_name='Skills Weight'),
        ),
    ]
