# Generated by Django 6.0.3 on 2026-09-29 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0035_job_education_weight_job_experience_weight_and_more"),
        ("jobs", "0035_job_vacancies"),
    ]

    operations = []
