# Generated by Django 6.0.3 on 2026-09-30 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0036_merge_20260929_1308"),
        ("jobs", "0036_merge_20260930_1528"),
    ]

    operations = []
