-- ============================================================
-- DBRecruitAI MySQL -> Supabase PostgreSQL schema
-- ============================================================

BEGIN;

-- ============================================================
-- applicant
-- ============================================================

CREATE TABLE IF NOT EXISTS applicant (
    name varchar(200) NOT NULL,
    email varchar(200) NOT NULL,
    applied_jod varchar(200) NOT NULL
);

-- ============================================================
-- Django Content Types
-- ============================================================

CREATE TABLE IF NOT EXISTS django_content_type (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_label varchar(100) NOT NULL,
    model varchar(100) NOT NULL,
    CONSTRAINT django_content_type_app_label_model_uniq
        UNIQUE (app_label, model)
);

-- ============================================================
-- Django Groups
-- ============================================================

CREATE TABLE IF NOT EXISTS auth_group (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(150) NOT NULL,
    CONSTRAINT auth_group_name_uniq UNIQUE (name)
);

-- ============================================================
-- Django Permissions
-- ============================================================

CREATE TABLE IF NOT EXISTS auth_permission (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    content_type_id integer NOT NULL,

    codename varchar(100) NOT NULL,

    CONSTRAINT auth_permission_content_type_fk
        FOREIGN KEY (content_type_id)
        REFERENCES django_content_type(id),

    CONSTRAINT auth_permission_content_type_codename_uniq
        UNIQUE (content_type_id, codename)
);

-- ============================================================
-- Django Users
-- ============================================================

CREATE TABLE IF NOT EXISTS auth_user (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    password varchar(128) NOT NULL,
    last_login timestamp(6) with time zone,
    is_superuser boolean NOT NULL,
    username varchar(150) NOT NULL,
    first_name varchar(150) NOT NULL,
    last_name varchar(150) NOT NULL,
    email varchar(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp(6) with time zone NOT NULL,

    CONSTRAINT auth_user_username_uniq
        UNIQUE (username)
);

-- ============================================================
-- Django Group Permissions
-- ============================================================

CREATE TABLE IF NOT EXISTS auth_group_permissions (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id integer NOT NULL,
    permission_id integer NOT NULL,

    CONSTRAINT auth_group_permissions_group_fk
        FOREIGN KEY (group_id)
        REFERENCES auth_group(id),

    CONSTRAINT auth_group_permissions_permission_fk
        FOREIGN KEY (permission_id)
        REFERENCES auth_permission(id),

    CONSTRAINT auth_group_permissions_group_permission_uniq
        UNIQUE (group_id, permission_id)
);

-- ============================================================
-- Django User Groups
-- ============================================================

CREATE TABLE IF NOT EXISTS auth_user_groups (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL,
    group_id integer NOT NULL,

    CONSTRAINT auth_user_groups_user_fk
        FOREIGN KEY (user_id)
        REFERENCES auth_user(id),

    CONSTRAINT auth_user_groups_group_fk
        FOREIGN KEY (group_id)
        REFERENCES auth_group(id),

    CONSTRAINT auth_user_groups_user_group_uniq
        UNIQUE (user_id, group_id)
);

-- ============================================================
-- Django User Permissions
-- ============================================================

CREATE TABLE IF NOT EXISTS auth_user_user_permissions (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL,
    permission_id integer NOT NULL,

    CONSTRAINT auth_user_user_permissions_user_fk
        FOREIGN KEY (user_id)
        REFERENCES auth_user(id),

    CONSTRAINT auth_user_user_permissions_permission_fk
        FOREIGN KEY (permission_id)
        REFERENCES auth_permission(id),

    CONSTRAINT auth_user_user_permissions_user_permission_uniq
        UNIQUE (user_id, permission_id)
);

-- ============================================================
-- Django Migrations
-- ============================================================

CREATE TABLE IF NOT EXISTS django_migrations (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app varchar(255) NOT NULL,
    name varchar(255) NOT NULL,
    applied timestamp(6) with time zone NOT NULL
);

-- ============================================================
-- Django Sessions
-- ============================================================

CREATE TABLE IF NOT EXISTS django_session (
    session_key varchar(40) PRIMARY KEY,
    session_data text NOT NULL,
    expire_date timestamp(6) with time zone NOT NULL
);

CREATE INDEX IF NOT EXISTS django_session_expire_date_idx
    ON django_session(expire_date);

-- ============================================================
-- Django Admin Log
-- ============================================================

CREATE TABLE IF NOT EXISTS django_admin_log (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action_time timestamp(6) with time zone NOT NULL,
    object_id text,
    object_repr varchar(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,

    CONSTRAINT django_admin_log_content_type_fk
        FOREIGN KEY (content_type_id)
        REFERENCES django_content_type(id),

    CONSTRAINT django_admin_log_user_fk
        FOREIGN KEY (user_id)
        REFERENCES auth_user(id)
);

-- ============================================================
-- Jobs
-- ============================================================

CREATE TABLE IF NOT EXISTS jobs_job (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar(100) NOT NULL,
    department varchar(100) NOT NULL,
    job_type varchar(20) NOT NULL,
    description text NOT NULL,
    posted_date date NOT NULL,
    status varchar(20) NOT NULL
);

-- ============================================================
-- Job Requirements
-- ============================================================

CREATE TABLE IF NOT EXISTS jobs_requirement (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text varchar(255) NOT NULL,
    job_id bigint NOT NULL,

    CONSTRAINT jobs_requirement_job_fk
        FOREIGN KEY (job_id)
        REFERENCES jobs_job(id)
);

CREATE INDEX IF NOT EXISTS jobs_requirement_job_id_idx
    ON jobs_requirement(job_id);

-- ============================================================
-- Applications
-- ============================================================

CREATE TABLE IF NOT EXISTS jobs_application (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    application_id varchar(12) NOT NULL,
    first_name varchar(100) NOT NULL,
    middle_initial varchar(10) NOT NULL,
    last_name varchar(100) NOT NULL,
    email varchar(254) NOT NULL,
    phone varchar(20) NOT NULL,
    resume varchar(100) NOT NULL,

    resume_processed boolean NOT NULL,
    status varchar(20) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,

    job_id bigint NOT NULL,

    ai_score integer NOT NULL,
    ai_strengths text NOT NULL,
    ai_summary text NOT NULL,
    ai_weaknesses text NOT NULL,

    interview_scheduled boolean NOT NULL,

    CONSTRAINT jobs_application_application_id_uniq
        UNIQUE (application_id),

    CONSTRAINT jobs_application_job_fk
        FOREIGN KEY (job_id)
        REFERENCES jobs_job(id)
);

CREATE INDEX IF NOT EXISTS jobs_application_job_id_idx
    ON jobs_application(job_id);

-- ============================================================
-- Interviews
-- ============================================================

CREATE TABLE IF NOT EXISTS hr_interview (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    interview_type varchar(30) NOT NULL,
    interviewer varchar(100) NOT NULL,
    date date NOT NULL,
    time time(6) NOT NULL,
    location varchar(255) NOT NULL,
    notes text NOT NULL,
    status varchar(20) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL
);

-- ============================================================
-- Interview <-> Application
-- ============================================================

CREATE TABLE IF NOT EXISTS hr_interview_applicants (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    interview_id bigint NOT NULL,
    application_id bigint NOT NULL,

    CONSTRAINT hr_interview_applicants_interview_fk
        FOREIGN KEY (interview_id)
        REFERENCES hr_interview(id),

    CONSTRAINT hr_interview_applicants_application_fk
        FOREIGN KEY (application_id)
        REFERENCES jobs_application(id),

    CONSTRAINT hr_interview_applicants_interview_application_uniq
        UNIQUE (interview_id, application_id)
);

COMMIT;