# Generated by Django 6.0.3 on 2026-09-23 04:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0001_initial"),
        ("jobs", "0033_alter_application_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CandidateEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("evaluator_name", models.CharField(blank=True, max_length=150)),
                (
                    "interview_mode",
                    models.CharField(
                        choices=[
                            ("Face-to-Face", "Face-to-Face"),
                            ("Online", "Online (Google Meet / Zoom)"),
                            ("Phone Call", "Phone Call"),
                        ],
                        default="Face-to-Face",
                        max_length=30,
                    ),
                ),
                (
                    "evaluation_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                ("technical_competence", models.IntegerField(default=3)),
                ("communication_skills", models.IntegerField(default=3)),
                ("problem_solving", models.IntegerField(default=3)),
                ("cultural_fit", models.IntegerField(default=3)),
                ("leadership_potential", models.IntegerField(default=3)),
                (
                    "overall_rating",
                    models.DecimalField(decimal_places=1, default=3.0, max_digits=4),
                ),
                ("strengths_notes", models.TextField(blank=True)),
                ("weaknesses_notes", models.TextField(blank=True)),
                ("general_notes", models.TextField(blank=True)),
                (
                    "audio_file",
                    models.FileField(
                        blank=True, null=True, upload_to="interview_audio/%Y/%m/"
                    ),
                ),
                ("ai_audio_transcript", models.TextField(blank=True)),
                ("ai_audio_summary", models.TextField(blank=True)),
                ("ai_audio_score", models.IntegerField(default=0)),
                ("ai_audio_insights", models.JSONField(blank=True, default=dict)),
                ("expected_salary", models.CharField(blank=True, max_length=100)),
                ("notice_period", models.CharField(blank=True, max_length=100)),
                ("availability_date", models.CharField(blank=True, max_length=100)),
                (
                    "recommendation",
                    models.CharField(
                        choices=[
                            ("Strong Hire", "Strong Hire"),
                            ("Hire", "Hire"),
                            ("Hold", "Hold / Further Review"),
                            ("No Hire", "Do Not Hire"),
                        ],
                        default="Hire",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Draft", "Draft"), ("Completed", "Completed")],
                        default="Completed",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluation",
                        to="jobs.application",
                    ),
                ),
                (
                    "evaluator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evaluations_conducted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "interview",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evaluations",
                        to="hr.interview",
                    ),
                ),
            ],
            options={
                "ordering": ["-evaluation_date", "-created_at"],
            },
        ),
    ]
