# Generated by Django 6.0.3 on 2026-09-25 10:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0002_candidateevaluation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(blank=True, max_length=150)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("STATUS_CHANGE", "Status Change"),
                            ("REJECT_APPLICATION", "Application Rejected"),
                            ("SHORTLIST_APPLICATION", "Application Shortlisted"),
                            ("HIRE_APPLICATION", "Application Hired"),
                            ("INTERVIEW_SCHEDULED", "Interview Scheduled"),
                            ("INTERVIEW_RESCHEDULED", "Interview Rescheduled"),
                            ("INTERVIEW_CANCELLED", "Interview Cancelled"),
                            ("EVALUATION_COMPLETED", "Evaluation Completed"),
                            ("EVALUATION_RESET", "Evaluation Reset"),
                            ("JOB_CREATED", "Job Created"),
                            ("JOB_UPDATED", "Job Updated"),
                            ("DEPARTMENT_CREATED", "Department Created"),
                            ("EMAIL_SENT", "Candidate Email Sent"),
                            ("HR_LOGIN", "HR Staff Login"),
                            ("HR_LOGOUT", "HR Staff Logout"),
                            ("OTHER", "Other HR Action"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("action_display", models.CharField(blank=True, max_length=100)),
                (
                    "target_model",
                    models.CharField(blank=True, db_index=True, max_length=50),
                ),
                ("target_id", models.CharField(blank=True, max_length=50)),
                ("target_repr", models.CharField(blank=True, max_length=255)),
                ("details", models.TextField(blank=True)),
                ("ip_address", models.CharField(blank=True, max_length=45, null=True)),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hr_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["action", "-timestamp"],
                        name="hr_auditlog_action_4b59f7_idx",
                    ),
                    models.Index(
                        fields=["user", "-timestamp"],
                        name="hr_auditlog_user_id_cd333a_idx",
                    ),
                ],
            },
        ),
    ]
