# Generated by Django 6.0.3 on 2026-09-26 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0003_auditlog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="candidateevaluation",
            name="final_decision",
            field=models.CharField(
                blank=True,
                choices=[("Hired", "Hired"), ("Not Hired", "Not Hired")],
                db_index=True,
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="candidateevaluation",
            name="final_decision_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="final_decisions_conducted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="candidateevaluation",
            name="final_decision_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="candidateevaluation",
            name="final_decision_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("STATUS_CHANGE", "Status Change"),
                    ("REJECT_APPLICATION", "Application Rejected"),
                    ("SHORTLIST_APPLICATION", "Application Shortlisted"),
                    ("HIRE_APPLICATION", "Application Hired"),
                    ("FINAL_DECISION_HIRED", "Final Decision: Hired"),
                    ("FINAL_DECISION_NOT_HIRED", "Final Decision: Not Hired"),
                    ("INTERVIEW_SCHEDULED", "Interview Scheduled"),
                    ("INTERVIEW_RESCHEDULED", "Interview Rescheduled"),
                    ("INTERVIEW_CANCELLED", "Interview Cancelled"),
                    ("EVALUATION_COMPLETED", "Evaluation Completed"),
                    ("EVALUATION_RESET", "Evaluation Reset"),
                    ("JOB_CREATED", "Job Created"),
                    ("JOB_UPDATED", "Job Updated"),
                    ("DEPARTMENT_CREATED", "Department Created"),
                    ("EMAIL_SENT", "Candidate Email Sent"),
                    ("HR_LOGIN", "HR Staff Login"),
                    ("HR_LOGOUT", "HR Staff Logout"),
                    ("OTHER", "Other HR Action"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
