# Generated by Django 6.0.3 on 2026-09-26 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0004_candidateevaluation_final_decision_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interview",
            name="status",
            field=models.CharField(
                choices=[
                    ("Scheduled", "Scheduled"),
                    ("Rescheduled", "Rescheduled"),
                    ("Ongoing", "Ongoing"),
                    ("Completed", "Completed"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Scheduled",
                max_length=20,
            ),
        ),
    ]
