# Generated by Django 6.0.3 on 2026-09-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0006_hrnotification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hrnotification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("NEW_APPLICATION", "New Application Submitted"),
                    ("VIDEO_INTERVIEW_COMPLETED", "Video Interview Completed"),
                    ("INTERVIEW_SCHEDULED", "Interview Scheduled"),
                    ("EVALUATION_COMPLETED", "Evaluation Completed"),
                    ("HR_ACTION", "HR Team Action"),
                    ("SYSTEM", "System Alert"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
