# Generated by Django 6.0.3 on 2026-09-27 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0007_alter_hrnotification_notification_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="hrnotification",
            name="read_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="read_hr_notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="HRActionLock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_model",
                    models.CharField(
                        db_index=True, default="Application", max_length=50
                    ),
                ),
                ("target_id", models.PositiveIntegerField(db_index=True)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("SCHEDULE", "Interview Scheduling"),
                            ("RESCHEDULE", "Interview Rescheduling"),
                            ("FINAL_DECISION", "Final Hiring Decision"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("user_name", models.CharField(max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hr_action_locks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["target_model", "target_id", "expires_at"],
                        name="hr_hraction_target__3aba05_idx",
                    )
                ],
                "unique_together": {("target_model", "target_id", "action_type")},
            },
        ),
    ]
