# Generated by Django 6.0.3 on 2026-09-29 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0008_hrnotification_read_by_hractionlock"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidateevaluation",
            name="is_evaluating",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
