# Generated by Django 6.0.3 on 2026-08-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantprofile',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
