# Generated by Django 6.0.3 on 2026-08-19 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_applicantprofile_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantprofile',
            name='resume_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='resume_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='resume_processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='resume_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='default_resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
