# Generated by Django 6.0.3 on 2026-09-05 19:46

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_applicantprofile_resume_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantprofile',
            name='default_resume',
            field=models.FileField(blank=True, null=True, upload_to=accounts.models.applicant_resume_upload_path),
        ),
    ]
