# Generated by Django 6.0.3 on 2026-09-05 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("jobs", "0016_application_jobs_applic_status_f83260_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BehavioralQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.CharField(max_length=500)),
                (
                    "category",
                    models.CharField(blank=True, default="General", max_length=100),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave blank to make this a default question across all jobs.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="behavioral_questions",
                        to="jobs.job",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InterviewSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending (Not Started)"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("ABANDONED", "Abandoned"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "final_score",
                    models.IntegerField(
                        blank=True, help_text="Score between 50 and 100", null=True
                    ),
                ),
                ("overall_feedback", models.TextField(blank=True)),
                ("overall_summary", models.TextField(blank=True)),
                ("ai_analyzed", models.BooleanField(default=False)),
                (
                    "can_retake",
                    models.BooleanField(
                        default=False,
                        help_text="Set by HR to allow applicant to retake interview after technical issues.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_interview",
                        to="jobs.application",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InterviewResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_number", models.IntegerField(help_text="1 to 5")),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("INTRO", "Introduction Question"),
                            ("BEHAVIORAL", "Behavioral Question"),
                        ],
                        default="BEHAVIORAL",
                        max_length=20,
                    ),
                ),
                ("question_text", models.CharField(max_length=500)),
                (
                    "video_clip",
                    models.FileField(
                        blank=True, null=True, upload_to="interview_videos/clips/"
                    ),
                ),
                ("skipped", models.BooleanField(default=False)),
                ("duration_seconds", models.IntegerField(default=0)),
                (
                    "score",
                    models.IntegerField(
                        blank=True, help_text="Question score 50-100", null=True
                    ),
                ),
                ("transcript", models.TextField(blank=True)),
                ("feedback", models.TextField(blank=True)),
                ("strengths", models.TextField(blank=True)),
                ("improvements", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="video_interview.interviewsession",
                    ),
                ),
            ],
            options={
                "ordering": ["question_number"],
                "unique_together": {("session", "question_number")},
            },
        ),
    ]
