# Generated by Django 6.0.3 on 2026-09-05 19:46

import video_interview.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_interview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewresponse',
            name='video_clip',
            field=models.FileField(blank=True, null=True, upload_to=video_interview.models.interview_video_upload_path),
        ),
    ]
